CREATE DATABASE [search_engine]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'search_engine', FILENAME = N'D:\LongBeach\Sem2-Summer\SearchEngineProject\Database\search_engine.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'search_engine_log', FILENAME = N'D:\LongBeach\Sem2-Summer\SearchEngineProject\Database\search_engine_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [search_engine] SET COMPATIBILITY_LEVEL = 150
GO
ALTER DATABASE [search_engine] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [search_engine] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [search_engine] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [search_engine] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [search_engine] SET ARITHABORT OFF 
GO
ALTER DATABASE [search_engine] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [search_engine] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [search_engine] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [search_engine] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [search_engine] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [search_engine] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [search_engine] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [search_engine] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [search_engine] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [search_engine] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [search_engine] SET  DISABLE_BROKER 
GO
ALTER DATABASE [search_engine] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [search_engine] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [search_engine] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [search_engine] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [search_engine] SET  READ_WRITE 
GO
ALTER DATABASE [search_engine] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [search_engine] SET  MULTI_USER 
GO
ALTER DATABASE [search_engine] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [search_engine] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [search_engine] SET DELAYED_DURABILITY = DISABLED 
GO
USE [search_engine]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [search_engine]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [search_engine] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
